### ISSUE TITLE
Move to @resultBuilder API

### ISSUE THREAD

**Issue by robb** [robb/Swim#19]
`@_functionBuilder` is now [`@resultBuilder`](https://github.com/apple/swift-evolution/blob/main/proposals/0289-result-builders.md), the API should be updated accordingly.

**Comment by kevinrenskers** [comment]
Could you please release a new version? I can't depend on just the main branch, as then my packages also have to be used as a branch, and can't be versioned.

**Comment by robb** [comment]
Try 0.2.0
