### ISSUE TITLE
Minimum Swift version is now 5.4

### ISSUE THREAD

**Issue by kevinrenskers** [robb/Swim#32]
Because of `@resultBuilder`, the minimum Swift version is now 5.4. So I think that means that Package.swift should be updated? Specifically the first line: `swift-tools-version:5.1`.

**Comment by robb** [comment]
Do you have to do that manually or can you have it regenerated from the toolchain in a predictable manner?

**Comment by kevinrenskers** [comment]
I think it has to be done manually.

**Comment by robb** [comment]
Should be better now.

**Comment by robb** [comment]
Feel free to reopen this if I messed up.
